########################################################################
# Copyright (c) 1988-2019 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 4/6/2019
#
# generic Gcc Makefile for patrona Executable patrona
########################################################################


#
# target
#
patrona_exe_EXETARGET = patrona

########################################################################

#
# user c++ flags
#
patrona_exe_USRCXXFLAGS += \
${patrona_USRCXXFLAGS} \

#
# user defines
#
patrona_exe_USRDEFINES += \
${patrona_USRDEFINES} \

#
# user includes
#
patrona_exe_USRINCLUDES += \
${patrona_USRINCLUDES} \

#
# user libdirs
#
patrona_exe_USRLIBDIRS += \
${patrona_USRLIBDIRS} \

########################################################################

#
# Executable .c sources
#
#patrona_exe_EXE_C_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.c \

#
# Executable .cc sources
#
#patrona_exe_EXE_CC_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.cc \

#
# Executable .cxx sources
#
#patrona_exe_EXE_CXX_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.cxx \

#
# Executable .cpp sources
#
patrona_exe_EXE_CPP_SOURCES += \
${PATRONA_SRC}/patrona/console/Main_main.cpp \
${PATRONA_SRC}/patrona/app/console/patrona/Main.cpp \

#
# Executable .m sources
#
#patrona_exe_EXE_M_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.m \

#
# Executable .mm sources
#
#patrona_exe_EXE_MM_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.mm \


########################################################################

#
# Executable libraries
#
patrona_exe_LIBS += \
${patrona_LIBS}



