########################################################################
# Copyright (c) 1988-2019 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 4/6/2019
#
# generic Gcc Makefile for patrona Library libpatrona
########################################################################


#
# target
#
libpatrona_LIBTARGET = libpatrona.${LIBEXT}

########################################################################

#
# user c++ flags
#
libpatrona_USRCXXFLAGS += \
${patrona_USRCXXFLAGS} \

#
# user defines
#
libpatrona_USRDEFINES += \
${patrona_USRDEFINES} \

#
# user includes
#
libpatrona_USRINCLUDES += \
${patrona_USRINCLUDES} \

#
# user libdirs
#
libpatrona_USRLIBDIRS += \
${patrona_USRLIBDIRS} \

########################################################################

#
# Library .c sources
#
#libpatrona_LIB_C_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.c \

#
# Library .cc sources
#
#libpatrona_LIB_CC_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.cc \

#
# Library .cxx sources
#
#libpatrona_LIB_CXX_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.cxx \

#
# Library .cpp sources
#
libpatrona_LIB_CPP_SOURCES += \
${PATRONA_SRC}/patrona/base/Acquired.cpp \
${PATRONA_SRC}/patrona/base/Array.cpp \
${PATRONA_SRC}/patrona/base/Attached.cpp \
${PATRONA_SRC}/patrona/base/Base.cpp \
${PATRONA_SRC}/patrona/base/Chars.cpp \
${PATRONA_SRC}/patrona/base/Created.cpp \
${PATRONA_SRC}/patrona/base/Joined.cpp \
${PATRONA_SRC}/patrona/base/Locked.cpp \
${PATRONA_SRC}/patrona/base/Opened.cpp \
${PATRONA_SRC}/patrona/base/Sleep.cpp \
${PATRONA_SRC}/patrona/base/String.cpp \
${PATRONA_SRC}/patrona/base/Waited.cpp \
\
${PATRONA_SRC}/patrona/io/crt/file/Mode.cpp \
${PATRONA_SRC}/patrona/io/crt/file/Reader.cpp \
${PATRONA_SRC}/patrona/io/crt/file/Stream.cpp \
${PATRONA_SRC}/patrona/io/crt/file/Writer.cpp \
${PATRONA_SRC}/patrona/io/Writers.cpp \
${PATRONA_SRC}/patrona/io/Logger.cpp \
\
${PATRONA_SRC}/patrona/console/Argv.cpp \
${PATRONA_SRC}/patrona/console/getopt/Main.cpp \
${PATRONA_SRC}/patrona/console/getopt/MainOpt.cpp \
${PATRONA_SRC}/patrona/console/IO.cpp \
\
${PATRONA_SRC}/patrona/lib/patrona/Version.cpp \

#
# Library .m sources
#
#libpatrona_LIB_M_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.m \

#
# Library .mm sources
#
#libpatrona_LIB_MM_SOURCES += \
#${PATRONA_SRC}/patrona/base/Base.mm \


########################################################################




